### ISSUE TITLE
Ability to open compare from the gitease sidebar?

### ISSUE THREAD

**Issue by ItsCubeTime** [rkotze/git-ease#14]

**Comment by rkotze** [comment]
delivered in version 0.4.0

**Comment by ItsCubeTime** [comment]
> delivered in version 0.4.0

Oh wow, nice update!

If I were to add to the feature request it would be nice if one could also select a different commit to compare to, maybe like a button next to the new "Open file" button that once pressed will ask you to select the commit you wanna compare to.
