### ISSUE TITLE
Search by tag, name and commit description?

### ISSUE THREAD

**Issue by ItsCubeTime** [rkotze/git-ease#15]
To demonstrate what it _could_ (if the API supports it) look like (which would either sort of filter by the given search words, so in the example "Ep 21" would display first or be the only commit included in the list)

![image](https://user-images.githubusercontent.com/20190653/114352196-df97b700-9b6b-11eb-87d4-e13b5e478988.png)

**Comment by rkotze** [comment]
Yeah, I think searching commits will be a valuable feature to add. Will add this to the to-do list.

**Comment by rkotze** [comment]
How to search Git commit messages:

`git log --grep "API naming"`
